[default]
address = "127.0.0.1"
port = 3000
workers = 8
keep_alive = 5
log_level = "normal"

[debug]
address = "127.0.0.1"
port = 3000
workers = 4
keep_alive = 5
log_level = "debug"

[release]
address = "0.0.0.0"
port = 3000
workers = 16
keep_alive = 5
log_level = "critical"
